language: python
python: 3.6


install:
  - "pip install -U pip"
  - "pip install lektor"

script : "lektor plugins reinstall"
script: "lektor clean --yes"
script: "lektor build -f minify --no-prune"
deploy:
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: main
